### ISSUE TITLE
请问那个自动生成的侧边栏怎么用得

### ISSUE THREAD

**Issue by qianzai** [shirayner/snote#1]
是npm install 安装一下vuepress-plugin-auto-sideba插件
然后在plugins进行这个配置，还要进行哪些操作吗
![image](https://user-images.githubusercontent.com/46664739/122023979-9decec00-cdfa-11eb-9ca1-6f0b920fb28a.png)

**Comment by shirayner** [comment]
见： https://shirayner.github.io/snote/cs/backend/dev-tools/07_ji-yu-vuepresshe-githubda-jian-ge-ren-bo-ke-zhan-dian.html#_5-%E7%9B%B8%E5%85%B3%E6%8F%92%E4%BB%B6

![image](https://user-images.githubusercontent.com/11574340/122213043-1a56fc00-cedb-11eb-8ee2-d925a7edbc74.png)

然后就什么都不用做就可以了。

具体可参见官网：https://shanyuhai123.github.io/vuepress-plugin-auto-sidebar/
